### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by rcnerd** [KRHS-GameProgramming-2015/Plane-Game#8]
CAN"T PUSH 403 Error
![capture](https://cloud.githubusercontent.com/assets/12915987/16242883/ac873bfe-37c2-11e6-9fa9-a986a36f76a6.PNG)

**Comment by cspoonerKRHS** [comment]
Make sure it's not git by pushing your other code up

**Comment by cspoonerKRHS** [comment]
Did you get it working?

**Comment by rcnerd** [comment]
Idk yet.

Wells, Hunter

**Comment by cspoonerKRHS** [comment]
I pushed a test in the main file and it seemed to go

On Tue, Jun 21, 2016 at 4:03 PM, Christopher Spooner <cspooner@kearsarge.org

> wrote:
> 
> Make sure it's not git by pushing your other code up

**Comment by rcnerd** [comment]
Okay I'll recheck repository url

Wells, Hunter

**Comment by rcnerd** [comment]
deleted and re added repository on my side. I still get the same error... about to check user name and password...

**Comment by cspoonerKRHS** [comment]
Hmmm

**Comment by rcnerd** [comment]
it will only let me fetch not pull aswell

**Comment by rcnerd** [comment]
I am obviously a contributor

**Comment by rcnerd** [comment]
i'm going to create a fork that I own and see if that fixes anything

**Comment by cspoonerKRHS** [comment]
I moved you from write to admin...try it now

**Comment by rcnerd** [comment]
Worked in fork

**Comment by cspoonerKRHS** [comment]
K... This will be a good test of branches and pull requests... Signal me to
pull when you are in a good state!

**Comment by rcnerd** [comment]
didnt work in orginal even after change to admin

**Comment by rcnerd** [comment]
ypu can pull fork

**Comment by rcnerd** [comment]
maybe it's best i work in a fork anyway. just to maintain the original and have my personal one... idk

**Comment by rcnerd** [comment]
looks like it is the repository... i change the remote on the repository that wasn't working to the fork remote and it still would not push... recreating repository now

**Comment by rcnerd** [comment]
nope....

**Comment by rcnerd** [comment]
I'll just work in the fork... it's a better place anyway

**Comment by rcnerd** [comment]
https://github.com/rcnerd/Plane-Game
